version: '2.1'

services:
  user-service:
    build: user-service
    mem_limit: 350m
    environment:
      - SPRING_PROFILES_ACTIVE=docker

  external-data:
    build: external-data
    mem_limit: 350m
    environment:
      - SPRING_PROFILES_ACTIVE=docker

  gateway:
    build: gateway
    mem_limit: 350m
    environment:
      - SPRING_PROFILES_ACTIVE=docker

  eurekaserver:
    build: eurekaserver
    mem_limit: 350m
    ports:
      - "8080:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=docker
