version: '2.1'

services:
  eureka:
    build: eurekaserver
    mem_limit: 350m
    environment:
    - JAVA_OPTS=-Djdk.tls.client.protocols=TLSv1.2
    ports:
      - "8761:8761"

  user-service:
    build: user-service
    mem_limit: 350m
    ports:
      - "7001:8080"
    volumes:
      - ./logs:/log
    environment:
      - SPRING_PROFILES_ACTIVE=docker
      - JAVA_OPTS=-Djdk.tls.client.protocols=TLSv1.2
      
  gateway:
    environment:
      - SPRING_PROFILES_ACTIVE=docker
      - JAVA_OPTS=-Djdk.tls.client.protocols=TLSv1.2
    build: gateway
    mem_limit: 350m
    ports:
      - "8080:8080"
      
  trends:
    build: data-trends-predictions
    mem_limit: 350m
    ports:
      - "7002:8050"

  real-time-data-processor:
    build: real-time-data-processor
    mem_limit: 350m
    environment:
      - SPRING_PROFILES_ACTIVE=docker
    ports:
      - "8005:8080"