# This workflow will build a Java project with Maven, and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: Java CI with Maven

on:
  push:
    branches: [ project-deployment ]
  pull_request:
    branches: [ project-deployment ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 8
      uses: actions/setup-java@v2
      with:
        java-version: '8'
        distribution: 'temurin'
        cache: maven
    - name: Build server with Maven
      run: mvn -B package --file eurekaserver/pom.xml
    - name: Build utils with Maven
      run: mvn -B package --file utils/pom.xml
    - name: Build gateway with Maven
      run: mvn -B package --file gateway/pom.xml
    - name: Build user service with Maven
      run: mvn -B package --file user-service/pom.xml
    - name: Build external data with Maven
      run: mvn -B package --file external-data/pom.xml
